// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQWzObjKLx0Ulx8ApPDZrX_sU6l5PPA3A',
    appId: '1:698580767225:web:8670d8b70761308aa02d28',
    messagingSenderId: '698580767225',
    projectId: 'circle-e21b6',
    authDomain: 'circle-e21b6.firebaseapp.com',
    storageBucket: 'circle-e21b6.firebasestorage.app',
    measurementId: 'G-YRLNN4S8HD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxFF1YByi-eDQ9KNJZjl-TVP9EPKO6G1g',
    appId: '1:698580767225:android:08de1c441b67b491a02d28',
    messagingSenderId: '698580767225',
    projectId: 'circle-e21b6',
    storageBucket: 'circle-e21b6.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUfcMVRtALk-m-HjYpRlAurCZK10G_QFE',
    appId: '1:698580767225:ios:7de669925317c51ba02d28',
    messagingSenderId: '698580767225',
    projectId: 'circle-e21b6',
    storageBucket: 'circle-e21b6.firebasestorage.app',
    androidClientId: '698580767225-p4frff5103v3t7aaoh01ahlphafbopsp.apps.googleusercontent.com',
    iosBundleId: 'com.india.jana',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUfcMVRtALk-m-HjYpRlAurCZK10G_QFE',
    appId: '1:698580767225:ios:7de669925317c51ba02d28',
    messagingSenderId: '698580767225',
    projectId: 'circle-e21b6',
    storageBucket: 'circle-e21b6.firebasestorage.app',
    androidClientId: '698580767225-p4frff5103v3t7aaoh01ahlphafbopsp.apps.googleusercontent.com',
    iosBundleId: 'com.india.jana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQWzObjKLx0Ulx8ApPDZrX_sU6l5PPA3A',
    appId: '1:698580767225:web:be5ecff8209652c7a02d28',
    messagingSenderId: '698580767225',
    projectId: 'circle-e21b6',
    authDomain: 'circle-e21b6.firebaseapp.com',
    storageBucket: 'circle-e21b6.firebasestorage.app',
    measurementId: 'G-N8MX1DX0QE',
  );
}
